language: php  # specify your language
php: # specify options for your language
  # using major version aliases
- 5.6
- 7.0
- 7.1
- 5.5

matrix:
  allow_failures:
    - php: 5.5
    
install:
  - composer install --no-interaction
  
before_script:
  - mkdir -p build/logs
 
script:
  - vendor/bin/phpunit --configuration "$PWD/phpunit.xml" --coverage-text
  
after_success:
  - travis_retry php vendor/bin/coveralls -v