language: php  # specify your language
php: # specify options for your language
  # using major version aliases
- 5.6
- 7.0
- 7.1
before_script:
  - composer install
  
script: 
  - echo $PWD    
  - vendor/bin/phpunit --configuration ./test/phpunit.xml --coverage-text