<?php

namespace MNHcC\MinimalusLayoutilus\Reflection;

use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-06 at 16:20:04.
 */
class CallableReflectionObjectMethodTest extends TestCase {

    /**
     * @var CallableReflectionObjectMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {        
        $this->object = new CallableReflectionObjectMethod(new Test\ExampleClass(), 'foo');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke() {
        $actual = $this->object;
        $this->assertSame($actual(''), 'foo');
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::invokeStatic
     * @todo   Implement testInvokeStatic().
     */
    public function testInvokeStatic() {
        $this->setExpectedException(\ReflectionException::class);
        $this->assertInstanceOf(\ReflectionException::class, $this->object->invokeStatic());
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke() {
        $this->assertSame($this->object->invoke(''), 'foo');
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::setObject
     * @todo   Implement testSetObject().
     */
    public function testSetObject() {
        $this->assertTrue($this->object->setObject(new Test\ExampleClass()));
    }

}
