<?php

namespace MNHcC\MinimalusLayoutilus\Reflection;

use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-06 at 16:20:04.
 */
class ReflectionObjectMethodTest extends TestCase {

    /**
     * @var ReflectionObjectMethod
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {        
        $testClass = new Test\ExampleClass();
        $this->object = new ReflectionObjectMethod($testClass, 'foo');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke() {
        $actual = $this->object;
        $this->assertSame($actual(''), 'foo');
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::invokeStatic
     * @todo   Implement testInvokeStatic().
     */
    public function testInvokeStatic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MNHcC\MinimalusLayoutilus\Reflection\ReflectionObjectMethod::setObject
     * @todo   Implement testSetObject().
     */
    public function testSetObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
